[program:vrpfr-worker]
process_name=%(program_name)s_%(process_num)02d
command=php __APP_DIR__/artisan queue:work --sleep=3 --tries=3 --max-time=3600
directory=__APP_DIR__
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=__APP_DIR__/storage/logs/worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stopwaitsecs=3600
