<?php

namespace App\Http\Controllers;

use App\Models\AppSetting;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Inertia\Inertia;
use Inertia\Response;

class AppSettingsController extends Controller
{
    private const MOBILE_THEME_SETTING = 'mobile_theme_key';
    private const DEFAULT_MOBILE_THEME = 'vectora';

    public function developer(): Response
    {
        return Inertia::render('settings/developer', [
            'testDriverQuickLogin' => AppSetting::get('test_driver_quick_login', 'false') === 'true',
        ]);
    }

    public function updateDeveloper(Request $request)
    {
        AppSetting::set(
            'test_driver_quick_login',
            $request->boolean('test_driver_quick_login') ? 'true' : 'false',
        );

        return back();
    }

    public function mobileTheme(): Response
    {
        return Inertia::render('settings/mobile-theme', [
            'themeKey' => AppSetting::get(self::MOBILE_THEME_SETTING, self::DEFAULT_MOBILE_THEME),
            'themes' => self::mobileThemes(),
        ]);
    }

    public function updateMobileTheme(Request $request): RedirectResponse
    {
        $validated = $request->validate([
            'theme_key' => ['required', 'string', Rule::in(array_column(self::mobileThemes(), 'key'))],
        ]);

        AppSetting::set(self::MOBILE_THEME_SETTING, $validated['theme_key']);

        return back();
    }

    public function publicConfig(): JsonResponse
    {
        $themeKey = AppSetting::get(self::MOBILE_THEME_SETTING, self::DEFAULT_MOBILE_THEME);

        return response()->json([
            'ok' => true,
            'theme_key' => $themeKey,
            'theme_experience' => self::mobileThemeExperience($themeKey),
            'features' => [
                'test_driver_quick_login' => AppSetting::get('test_driver_quick_login', 'false') === 'true',
            ],
        ]);
    }

    private static function mobileThemes(): array
    {
        $themes = [
            [
                'key' => 'vectora',
                'name' => 'Vectora',
                'description' => 'Warm coral on deep midnight, the house signature.',
                'background' => '#0C0D10',
                'foreground' => '#F2EEE8',
                'card' => '#14171C',
                'muted' => '#1A1E24',
                'primary' => '#C89A63',
                'border' => '#2C3037',
                'success' => '#3FB684',
                'warning' => '#E0B15A',
                'charts' => ['#C89A63', '#6BAF9A', '#D2A45B', '#C58A7A', '#9BB36C'],
                'bodyFontFamily' => 'Inter',
                'displayFontFamily' => 'Playfair Display',
                'fullness' => 0.05,
            ],
            [
                'key' => 'midnight-noir',
                'name' => 'Midnight Noir',
                'description' => 'Polished obsidian and platinum, no warmth.',
                'background' => '#050507',
                'foreground' => '#EDEDED',
                'card' => '#101013',
                'muted' => '#18181C',
                'primary' => '#C0C0C8',
                'border' => '#2A2A30',
                'success' => '#74E5A0',
                'warning' => '#E0B15A',
                'charts' => ['#C0C0C8', '#6B7080', '#D0D0D6', '#8A8A92', '#ADADB5'],
                'bodyFontFamily' => 'Manrope',
                'displayFontFamily' => 'Bodoni Moda',
                'fullness' => -0.35,
                'bodyScale' => 0.98,
                'displayScale' => 0.95,
                'radiusScale' => 0.72,
                'iconScale' => 0.95,
            ],
            [
                'key' => 'cyberpunk-neon',
                'name' => 'Cyberpunk Neon',
                'description' => 'Hot pink, electric cyan and chrome glitch.',
                'background' => '#080315',
                'foreground' => '#E9F1FF',
                'card' => '#120824',
                'muted' => '#1A0E33',
                'primary' => '#FF2D95',
                'border' => '#2D1A4D',
                'success' => '#00FFD1',
                'warning' => '#FFD93D',
                'charts' => ['#FF2D95', '#00FFD1', '#B845FF', '#45D7FF', '#FFD93D'],
                'bodyFontFamily' => 'Space Grotesk',
                'displayFontFamily' => 'Major Mono Display',
                'fullness' => -0.2,
                'bodyScale' => 0.98,
                'displayScale' => 1.08,
                'radiusScale' => 0.68,
                'iconScale' => 1.05,
            ],
            [
                'key' => 'forest-deep',
                'name' => 'Forest Deep',
                'description' => 'Emerald canopy and damp moss.',
                'background' => '#0D1410',
                'foreground' => '#E8F5EC',
                'card' => '#131C17',
                'muted' => '#18241D',
                'primary' => '#6FBF8E',
                'border' => '#2A3D32',
                'success' => '#6FBF8E',
                'warning' => '#E0B15A',
                'charts' => ['#6FBF8E', '#9CC86F', '#C1A86B', '#82B89C', '#B8C58A'],
                'bodyFontFamily' => 'IBM Plex Sans',
                'displayFontFamily' => 'Cormorant Garamond',
                'fullness' => 0.15,
                'bodyScale' => 1.02,
                'radiusScale' => 1.15,
                'iconScale' => 1.02,
            ],
            [
                'key' => 'ocean-abyss',
                'name' => 'Ocean Abyss',
                'description' => 'Phosphorescent cyan over deep trench blue.',
                'background' => '#071018',
                'foreground' => '#E0F0FF',
                'card' => '#0E1A26',
                'muted' => '#14222F',
                'primary' => '#4FB6E5',
                'border' => '#1F3447',
                'success' => '#40D9B5',
                'warning' => '#FFC857',
                'charts' => ['#4FB6E5', '#40D9B5', '#FFC857', '#6B8EE0', '#94CFEB'],
                'bodyFontFamily' => 'Outfit',
                'displayFontFamily' => 'Lora',
                'fullness' => 0.05,
                'displayScale' => 1.02,
                'radiusScale' => 1.05,
            ],
            [
                'key' => 'sunset-coral',
                'name' => 'Sunset Coral',
                'description' => 'Pacific dusk: papaya, terracotta and ash.',
                'background' => '#1A0F0C',
                'foreground' => '#FFEFE5',
                'card' => '#241712',
                'muted' => '#2B1C16',
                'primary' => '#FF7A59',
                'border' => '#4A2E25',
                'success' => '#E5C45A',
                'warning' => '#FFB347',
                'charts' => ['#FF7A59', '#FFB347', '#E5C45A', '#E08070', '#FFC1A8'],
                'bodyFontFamily' => 'Plus Jakarta Sans',
                'displayFontFamily' => 'Italiana',
                'fullness' => 0.35,
                'bodyScale' => 1.03,
                'displayScale' => 1.08,
                'radiusScale' => 1.22,
                'iconScale' => 1.05,
            ],
            [
                'key' => 'royal-purple',
                'name' => 'Royal Purple',
                'description' => 'Velvet violet trimmed in old gold.',
                'background' => '#11081A',
                'foreground' => '#F2E8FF',
                'card' => '#1B0E2A',
                'muted' => '#231236',
                'primary' => '#B283F0',
                'border' => '#34204F',
                'success' => '#7CD9B5',
                'warning' => '#E5C56F',
                'charts' => ['#B283F0', '#E5C56F', '#7CD9B5', '#D8A0E0', '#9476B8'],
                'bodyFontFamily' => 'Albert Sans',
                'displayFontFamily' => 'Cormorant Garamond',
                'fullness' => 0.25,
                'displayScale' => 1.12,
                'radiusScale' => 1.18,
            ],
            [
                'key' => 'crimson-velvet',
                'name' => 'Crimson Velvet',
                'description' => 'Operatic claret over warm shadow.',
                'background' => '#120608',
                'foreground' => '#FFE8E8',
                'card' => '#1F0C10',
                'muted' => '#290F14',
                'primary' => '#D9495E',
                'border' => '#40191F',
                'success' => '#E5C45A',
                'warning' => '#FFB347',
                'charts' => ['#D9495E', '#E5C45A', '#FFB347', '#B85D70', '#E08090'],
                'bodyFontFamily' => 'Be Vietnam Pro',
                'displayFontFamily' => 'EB Garamond',
                'fullness' => 0.05,
                'bodyScale' => 1.01,
                'displayScale' => 1.07,
            ],
            [
                'key' => 'vaporwave',
                'name' => 'Vaporwave',
                'description' => 'Cassette futurism: pink, cyan, retrograde.',
                'background' => '#1A0E2A',
                'foreground' => '#E9D6FF',
                'card' => '#231340',
                'muted' => '#2A1A4A',
                'primary' => '#FF71CE',
                'border' => '#402863',
                'success' => '#01CDFE',
                'warning' => '#FFFB96',
                'charts' => ['#FF71CE', '#01CDFE', '#05FFA1', '#FFFB96', '#B967FF'],
                'bodyFontFamily' => 'Space Grotesk',
                'displayFontFamily' => 'Bodoni Moda',
                'fullness' => 0.2,
                'displayScale' => 1.14,
                'radiusScale' => 1.35,
                'iconScale' => 1.08,
            ],
            [
                'key' => 'espresso',
                'name' => 'Espresso',
                'description' => 'Bitter coffee, crema and warm leather.',
                'background' => '#14100C',
                'foreground' => '#EEDDC4',
                'card' => '#1F1813',
                'muted' => '#26201A',
                'primary' => '#D4A56B',
                'border' => '#3A2F25',
                'success' => '#9CB87A',
                'warning' => '#E5C45A',
                'charts' => ['#D4A56B', '#9CB87A', '#E5C45A', '#B88B5C', '#E5C49C'],
                'bodyFontFamily' => 'Outfit',
                'displayFontFamily' => 'Cormorant Garamond',
                'fullness' => 0.3,
                'bodyScale' => 1.02,
                'displayScale' => 1.04,
                'radiusScale' => 1.12,
                'iconScale' => 0.98,
            ],
            [
                'key' => 'dracula',
                'name' => 'Dracula',
                'description' => 'The classic vampire palette, ported to mobile.',
                'background' => '#282A36',
                'foreground' => '#F8F8F2',
                'card' => '#323440',
                'muted' => '#383A4B',
                'primary' => '#BD93F9',
                'border' => '#44475A',
                'success' => '#50FA7B',
                'warning' => '#FFB86C',
                'charts' => ['#BD93F9', '#50FA7B', '#FFB86C', '#FF79C6', '#8BE9FD'],
                'bodyFontFamily' => 'Fira Sans',
                'displayFontFamily' => 'DM Serif Display',
                'radiusScale' => 0.9,
            ],
            [
                'key' => 'tokyo-night',
                'name' => 'Tokyo Night',
                'description' => 'After-hours Shinjuku in cool blue and lavender.',
                'background' => '#1A1B26',
                'foreground' => '#A9B1D6',
                'card' => '#24283B',
                'muted' => '#2A2E42',
                'primary' => '#7AA2F7',
                'border' => '#3B4261',
                'success' => '#9ECE6A',
                'warning' => '#E0AF68',
                'charts' => ['#7AA2F7', '#9ECE6A', '#E0AF68', '#BB9AF7', '#7DCFFF'],
                'bodyFontFamily' => 'IBM Plex Sans',
                'displayFontFamily' => 'Space Mono',
                'fullness' => -0.25,
                'bodyScale' => 0.98,
                'displayScale' => 0.96,
                'radiusScale' => 0.8,
                'iconScale' => 0.95,
            ],
            [
                'key' => 'catppuccin-mocha',
                'name' => 'Catppuccin Mocha',
                'description' => 'Soothing pastel, the cult favourite.',
                'background' => '#1E1E2E',
                'foreground' => '#CDD6F4',
                'card' => '#252537',
                'muted' => '#313244',
                'primary' => '#CBA6F7',
                'border' => '#45475A',
                'success' => '#A6E3A1',
                'warning' => '#F9E2AF',
                'charts' => ['#CBA6F7', '#A6E3A1', '#F9E2AF', '#F5C2E7', '#89B4FA'],
                'bodyFontFamily' => 'Inter',
                'displayFontFamily' => 'DM Serif Display',
                'fullness' => 0.15,
                'displayScale' => 1.02,
                'radiusScale' => 1.2,
            ],
            [
                'key' => 'nord',
                'name' => 'Nord',
                'description' => 'Arctic Scandinavian: frost and snowstorm.',
                'background' => '#2E3440',
                'foreground' => '#ECEFF4',
                'card' => '#3B4252',
                'muted' => '#434C5E',
                'primary' => '#88C0D0',
                'border' => '#4C566A',
                'success' => '#A3BE8C',
                'warning' => '#EBCB8B',
                'charts' => ['#88C0D0', '#A3BE8C', '#EBCB8B', '#B48EAD', '#81A1C1'],
                'bodyFontFamily' => 'Manrope',
                'displayFontFamily' => 'Crimson Pro',
                'fullness' => 0.1,
                'radiusScale' => 1.05,
            ],
            [
                'key' => 'gruvbox',
                'name' => 'Gruvbox',
                'description' => 'Retro warm earthtones for the terminal soul.',
                'background' => '#282828',
                'foreground' => '#EBDBB2',
                'card' => '#32302F',
                'muted' => '#3C3836',
                'primary' => '#FE8019',
                'border' => '#504945',
                'success' => '#B8BB26',
                'warning' => '#FABD2F',
                'charts' => ['#FE8019', '#B8BB26', '#FABD2F', '#D3869B', '#83A598'],
                'bodyFontFamily' => 'Fira Sans',
                'displayFontFamily' => 'Lora',
                'fullness' => -0.1,
                'bodyScale' => 0.99,
                'radiusScale' => 0.85,
            ],
            [
                'key' => 'rose-pine',
                'name' => 'Rose Pine',
                'description' => 'Soho twilight: soft rose, gold and pine.',
                'background' => '#191724',
                'foreground' => '#E0DEF4',
                'card' => '#1F1D2E',
                'muted' => '#26233A',
                'primary' => '#EBBCBA',
                'border' => '#403A56',
                'success' => '#9CCFD8',
                'warning' => '#F6C177',
                'charts' => ['#EBBCBA', '#F6C177', '#9CCFD8', '#C4A7E7', '#31748F'],
                'bodyFontFamily' => 'Plus Jakarta Sans',
                'displayFontFamily' => 'Cormorant Garamond',
                'fullness' => 0.2,
                'bodyScale' => 1.01,
                'displayScale' => 1.08,
                'radiusScale' => 1.16,
            ],
            [
                'key' => 'solarized-dark',
                'name' => 'Solarized',
                'description' => 'Precision-engineered contrast and calm.',
                'background' => '#002B36',
                'foreground' => '#93A1A1',
                'card' => '#073642',
                'muted' => '#0E4252',
                'primary' => '#B58900',
                'border' => '#124555',
                'success' => '#859900',
                'warning' => '#CB4B16',
                'charts' => ['#B58900', '#859900', '#268BD2', '#D33682', '#2AA198'],
                'bodyFontFamily' => 'Source Sans 3',
                'displayFontFamily' => 'Crimson Pro',
                'fullness' => -0.3,
                'bodyScale' => 0.97,
                'displayScale' => 0.98,
                'radiusScale' => 0.78,
                'iconScale' => 0.95,
            ],
            [
                'key' => 'monochrome-ink',
                'name' => 'Monochrome Ink',
                'description' => 'Pure greyscale, sharp edges, brutalist.',
                'background' => '#0A0A0A',
                'foreground' => '#EEEEEE',
                'card' => '#141414',
                'muted' => '#1C1C1C',
                'primary' => '#FFFFFF',
                'border' => '#2A2A2A',
                'success' => '#EEEEEE',
                'warning' => '#B8B8B8',
                'charts' => ['#FFFFFF', '#B8B8B8', '#808080', '#595959', '#CCCCCC'],
                'bodyFontFamily' => 'Space Grotesk',
                'displayFontFamily' => 'Bebas Neue',
                'fullness' => -0.45,
                'bodyScale' => 0.96,
                'displayScale' => 1.1,
                'radiusScale' => 0.55,
                'iconScale' => 0.92,
            ],
            [
                'key' => 'honey-amber',
                'name' => 'Honey Amber',
                'description' => 'Sunlit honeycomb on burnt umber.',
                'background' => '#12100A',
                'foreground' => '#FFE8B8',
                'card' => '#1D1810',
                'muted' => '#241E14',
                'primary' => '#E8B14C',
                'border' => '#3A2F1C',
                'success' => '#B8C45A',
                'warning' => '#FFB347',
                'charts' => ['#E8B14C', '#FFB347', '#B8C45A', '#E08C5A', '#FFD08A'],
                'bodyFontFamily' => 'DM Sans',
                'displayFontFamily' => 'Italiana',
                'fullness' => 0.4,
                'bodyScale' => 1.03,
                'displayScale' => 1.08,
                'radiusScale' => 1.25,
                'iconScale' => 1.04,
            ],
            [
                'key' => 'mint-atelier',
                'name' => 'Mint Atelier',
                'description' => 'Cool mint and soft sage in low light.',
                'background' => '#0B1411',
                'foreground' => '#E5F5EE',
                'card' => '#101F1A',
                'muted' => '#152821',
                'primary' => '#7FE3B0',
                'border' => '#26443A',
                'success' => '#7FE3B0',
                'warning' => '#E5C66B',
                'charts' => ['#7FE3B0', '#E5C66B', '#A0D08A', '#6BBFB0', '#B8E0CC'],
                'bodyFontFamily' => 'DM Sans',
                'displayFontFamily' => 'Lora',
                'fullness' => 0.25,
                'bodyScale' => 1.02,
                'displayScale' => 1.02,
                'radiusScale' => 1.2,
            ],
            [
                'key' => 'aurora-slate',
                'name' => 'Aurora Slate',
                'description' => 'Polar blue, glacier mint and quiet night glass.',
                'background' => '#0B1020',
                'foreground' => '#EAF2FF',
                'card' => '#121A2E',
                'muted' => '#19243A',
                'primary' => '#64D2FF',
                'border' => '#2A3956',
                'success' => '#7DE2B8',
                'warning' => '#E6C36A',
                'charts' => ['#64D2FF', '#7DE2B8', '#E6C36A', '#A78BFA', '#93C5FD'],
                'bodyFontFamily' => 'Manrope',
                'displayFontFamily' => 'Crimson Pro',
                'fullness' => 0.1,
                'displayScale' => 1.03,
                'radiusScale' => 1.05,
                'iconScale' => 1.02,
            ],
        ];

        return array_map(
            fn (array $theme) => array_merge($theme, [
                'experience' => self::mobileThemeExperience($theme['key']),
            ]),
            $themes,
        );
    }

    private static function mobileThemeExperience(string $key): array
    {
        $profiles = [
            'vectora' => [
                'category' => 'Editorial ops',
                'dashboardLayout' => 'editorial',
                'navigation' => 'labeled-bar',
                'cardTreatment' => 'glass',
                'mapStyle' => 'dark',
                'markerStyle' => 'beacon',
                'routeLine' => 'glow',
                'backdrop' => 'cinematic',
                'motion' => 'calm',
                'glassIntensity' => 1.0,
                'glow' => 1.0,
                'mapContrast' => 1.0,
                'routeStroke' => 1.0,
                'density' => 0.05,
            ],
            'midnight-noir' => [
                'category' => 'Executive command',
                'dashboardLayout' => 'command',
                'navigation' => 'compact-dock',
                'cardTreatment' => 'outline',
                'mapStyle' => 'monochrome',
                'markerStyle' => 'pin',
                'routeLine' => 'thread',
                'backdrop' => 'void',
                'motion' => 'reduced',
                'glassIntensity' => 0.58,
                'glow' => 0.2,
                'mapContrast' => 1.2,
                'routeStroke' => 0.8,
                'density' => -0.35,
            ],
            'cyberpunk-neon' => [
                'category' => 'Dispatch arcade',
                'dashboardLayout' => 'radar',
                'navigation' => 'floating-dock',
                'cardTreatment' => 'neon',
                'mapStyle' => 'navigation-night',
                'markerStyle' => 'pulse',
                'routeLine' => 'neon',
                'backdrop' => 'grid',
                'motion' => 'kinetic',
                'glassIntensity' => 1.22,
                'glow' => 1.65,
                'mapContrast' => 1.35,
                'routeStroke' => 1.2,
                'density' => -0.2,
            ],
            'forest-deep' => [
                'category' => 'Field calm',
                'dashboardLayout' => 'field',
                'navigation' => 'quiet-bar',
                'cardTreatment' => 'organic',
                'mapStyle' => 'outdoors',
                'markerStyle' => 'leaf-pin',
                'routeLine' => 'canopy',
                'backdrop' => 'canopy',
                'motion' => 'calm',
                'glassIntensity' => 0.92,
                'glow' => 0.75,
                'mapContrast' => 0.94,
                'routeStroke' => 1.05,
                'density' => 0.15,
            ],
            'ocean-abyss' => [
                'category' => 'Live radar',
                'dashboardLayout' => 'radar',
                'navigation' => 'floating-dock',
                'cardTreatment' => 'glass',
                'mapStyle' => 'satellite',
                'markerStyle' => 'beacon',
                'routeLine' => 'sonar',
                'backdrop' => 'aurora',
                'motion' => 'fluid',
                'glassIntensity' => 1.08,
                'glow' => 1.25,
                'mapContrast' => 1.12,
                'routeStroke' => 1.12,
                'density' => 0.05,
            ],
            'sunset-coral' => [
                'category' => 'Warm route board',
                'dashboardLayout' => 'story',
                'navigation' => 'labeled-bar',
                'cardTreatment' => 'soft',
                'mapStyle' => 'streets',
                'markerStyle' => 'pill',
                'routeLine' => 'ribbon',
                'backdrop' => 'warm',
                'motion' => 'spring',
                'glassIntensity' => 1.14,
                'glow' => 0.95,
                'mapContrast' => 0.9,
                'routeStroke' => 1.18,
                'density' => 0.35,
            ],
            'royal-purple' => [
                'category' => 'Ceremonial console',
                'dashboardLayout' => 'story',
                'navigation' => 'floating-dock',
                'cardTreatment' => 'ornate',
                'mapStyle' => 'navigation-night',
                'markerStyle' => 'crest',
                'routeLine' => 'ribbon',
                'backdrop' => 'velvet',
                'motion' => 'slow',
                'glassIntensity' => 1.05,
                'glow' => 1.08,
                'mapContrast' => 1.05,
                'routeStroke' => 1.05,
                'density' => 0.25,
            ],
            'crimson-velvet' => [
                'category' => 'Incident desk',
                'dashboardLayout' => 'command',
                'navigation' => 'compact-dock',
                'cardTreatment' => 'dramatic',
                'mapStyle' => 'dark',
                'markerStyle' => 'alert',
                'routeLine' => 'ember',
                'backdrop' => 'velvet',
                'motion' => 'taut',
                'glassIntensity' => 0.96,
                'glow' => 1.15,
                'mapContrast' => 1.18,
                'routeStroke' => 1.0,
                'density' => 0.05,
            ],
            'vaporwave' => [
                'category' => 'Retro dispatch',
                'dashboardLayout' => 'radar',
                'navigation' => 'floating-dock',
                'cardTreatment' => 'neon',
                'mapStyle' => 'streets',
                'markerStyle' => 'pulse',
                'routeLine' => 'neon',
                'backdrop' => 'grid',
                'motion' => 'kinetic',
                'glassIntensity' => 1.28,
                'glow' => 1.55,
                'mapContrast' => 1.1,
                'routeStroke' => 1.16,
                'density' => 0.2,
            ],
            'espresso' => [
                'category' => 'Depot ledger',
                'dashboardLayout' => 'ledger',
                'navigation' => 'quiet-bar',
                'cardTreatment' => 'solid',
                'mapStyle' => 'outdoors',
                'markerStyle' => 'stamp',
                'routeLine' => 'ink',
                'backdrop' => 'warm',
                'motion' => 'calm',
                'glassIntensity' => 0.72,
                'glow' => 0.35,
                'mapContrast' => 0.88,
                'routeStroke' => 0.95,
                'density' => 0.3,
            ],
            'monochrome-ink' => [
                'category' => 'Brutalist manifest',
                'dashboardLayout' => 'ledger',
                'navigation' => 'compact-dock',
                'cardTreatment' => 'brutalist',
                'mapStyle' => 'monochrome',
                'markerStyle' => 'number',
                'routeLine' => 'thread',
                'backdrop' => 'void',
                'motion' => 'reduced',
                'glassIntensity' => 0.42,
                'glow' => 0.0,
                'mapContrast' => 1.3,
                'routeStroke' => 0.78,
                'density' => -0.45,
            ],
            'aurora-slate' => [
                'category' => 'Polar telemetry',
                'dashboardLayout' => 'radar',
                'navigation' => 'floating-dock',
                'cardTreatment' => 'glass',
                'mapStyle' => 'satellite',
                'markerStyle' => 'beacon',
                'routeLine' => 'sonar',
                'backdrop' => 'aurora',
                'motion' => 'fluid',
                'glassIntensity' => 1.1,
                'glow' => 1.35,
                'mapContrast' => 1.16,
                'routeStroke' => 1.08,
                'density' => 0.1,
            ],
        ];

        $fallbacks = [
            'dashboardLayout' => 'editorial',
            'navigation' => 'labeled-bar',
            'cardTreatment' => 'glass',
            'mapStyle' => 'dark',
            'markerStyle' => 'beacon',
            'routeLine' => 'glow',
            'backdrop' => 'cinematic',
            'motion' => 'calm',
            'glassIntensity' => 1.0,
            'glow' => 0.9,
            'mapContrast' => 1.0,
            'routeStroke' => 1.0,
            'density' => 0.0,
        ];

        return array_merge([
            'category' => 'Signature system',
        ], $fallbacks, $profiles[$key] ?? []);
    }
}
